version: '3.1'

services:
  app:
    build: 
      context: .
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    image: kepxo-front
    container_name: kepxo-front
    restart: always
    ports:
      - "5173:80"
